//
//  GreetMeTests-GreetMeFrameworkMocks.generated.swift
//  GreetMeFramework
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import GreetMeFramework
@testable import Mockingbird
import Foundation
import Swift
import SwiftUI

// No mockable types in 'GreetMeFramework'. Check that the module's source files have classes or
// protocols that are not private and not marked as final.
